"""Create rpm count model

Revision ID: 0b1142078094
Revises: bd06dd68a1c8
Create Date: 2023-09-28 15:18:39.570715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1142078094'
down_revision: Union[str, None] = 'bd06dd68a1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rpmcount', sa.Column('deviceSerial', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rpmcount', 'deviceSerial')
    # ### end Alembic commands ###
