"""Create rpm count model

Revision ID: 2142429254c5
Revises: 5f61fb393fee
Create Date: 2023-09-29 13:25:47.311448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2142429254c5'
down_revision: Union[str, None] = '5f61fb393fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rpmcount', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column('rpmcount', sa.Column('output', sa.Integer(), nullable=True))
    op.add_column('rpmcount', sa.Column('station', sa.Integer(), nullable=True))
    op.drop_column('rpmcount', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rpmcount', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('rpmcount', 'station')
    op.drop_column('rpmcount', 'output')
    op.drop_column('rpmcount', 'count')
    # ### end Alembic commands ###
