"""Create user table

Revision ID: 4911d0c534db
Revises: cf3a52a2e3d8
Create Date: 2023-09-27 14:04:12.189325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4911d0c534db'
down_revision: Union[str, None] = 'cf3a52a2e3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_id', table_name='devices')
    op.drop_index('ix_devices_name', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='devices_pkey')
    )
    op.create_index('ix_devices_name', 'devices', ['name'], unique=False)
    op.create_index('ix_devices_id', 'devices', ['id'], unique=False)
    # ### end Alembic commands ###
