"""Create user table

Revision ID: 5eadc792ef6c
Revises: d1bfe755ddb7
Create Date: 2023-09-27 14:18:50.654134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eadc792ef6c'
down_revision: Union[str, None] = 'd1bfe755ddb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('serial', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('devices', sa.Column('lineName', sa.Text(), nullable=True))
    op.add_column('devices', sa.Column('stationId', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('remark', sa.String(length=250), nullable=True))
    op.add_column('devices', sa.Column('version', sa.String(length=250), nullable=True))
    op.add_column('devices', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('devices', sa.Column('created_by', sa.String(length=250), nullable=True))
    op.add_column('devices', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.add_column('devices', sa.Column('update_by', sa.String(length=250), nullable=True))
    op.add_column('devices', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index('ix_devices_name', table_name='devices')
    op.drop_index('ix_devices_id', table_name='devices')
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=True)
    op.create_unique_constraint(None, 'devices', ['serial'])
    op.create_unique_constraint(None, 'devices', ['name'])
    op.add_column('users', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('update_by', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'update_by')
    op.drop_column('users', 'updated_date')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'created_date')
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.create_index('ix_devices_id', 'devices', ['id'], unique=False)
    op.create_index('ix_devices_name', 'devices', ['name'], unique=False)
    op.drop_column('devices', 'is_active')
    op.drop_column('devices', 'update_by')
    op.drop_column('devices', 'updated_date')
    op.drop_column('devices', 'created_by')
    op.drop_column('devices', 'created_date')
    op.drop_column('devices', 'version')
    op.drop_column('devices', 'remark')
    op.drop_column('devices', 'stationId')
    op.drop_column('devices', 'lineName')
    op.drop_column('devices', 'status')
    op.drop_column('devices', 'serial')
    # ### end Alembic commands ###
