"""Create rpm count model

Revision ID: bd06dd68a1c8
Revises: 5eadc792ef6c
Create Date: 2023-09-28 14:49:21.492416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd06dd68a1c8'
down_revision: Union[str, None] = '5eadc792ef6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpmcount',
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=250), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('update_by', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpmcount_id'), 'rpmcount', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rpmcount_id'), table_name='rpmcount')
    op.drop_table('rpmcount')
    # ### end Alembic commands ###
